name = "pipeable"
version = "0.1.0"
description = "An easy, efficient, fully-featured CI/CD pipeline in one executable."
target = "javascript"

[dependencies]
gleam_stdlib = { path = "../../../tmp/gleam_stdlib" }

[dev-dependencies]
